version: "3.1"
services:
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: 
            - --default-authentication-plugin=mysql_native_password
            - "--innodb_ft_min_token_size=1"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - data:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 3307:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password 
            UPLOAD_LIMIT: 3000000000
            MAX_EXECUTION_TIME: 0
volumes:
    data:

